FROM python:3.9-slim

WORKDIR /app

RUN apt-get update && apt-get install -y gcc && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY main_container/ ./main_container/
COPY database/ ./database/
COPY models/ ./models/

EXPOSE 5000

CMD ["python", "main_container/orchestrator.py"]
